spring.application.name=springbootkafka

# porta do consumer (servidor 2 apache)
spring.kafka.consumer.bootstrap-servers: localhost:9092

spring.kafka.consumer.group-id: myGround

spring.kafka.consumer.auto-offstet-reset: earliest

#configuracoo de string deserializer para consumer
spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# porta de conexao do produtor (server1 apache)
spring.kafka.bootstrap-servers=localhost:9092

# configuracao de string serializer para producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
